cargo-features = ["edition"]

[package]
name = "naive_ga_g3"
edition = '2018'
version = "0.1.0"
authors = ["rebo <rebo@fakeemail.org>"]
description = "Naive implmentation of the Geometric Algebra for G3"

[dependencies]
float-cmp = "0.4.0"


